steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/boe-backend/boe-backend:latest
      - .
images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/boe-backend/boe-backend:latest
